%Autogenerated Test File
function bool = A10(vZ, vT, trace)
	cpd11620_c0_ = getColumn(trace, 'cpd11620_c0_');
	cpd11621_c0_ = getColumn(trace, 'cpd11621_c0_');
	if(checkColumns(cpd11620_c0_,cpd11621_c0_) == 0)
		bool = -1;
	elseif((1)*vT(cpd11620_c0_) + (1)*vT(cpd11621_c0_) == (1)*vZ(cpd11620_c0_) + (1)*vZ(cpd11621_c0_))
		bool = 1;
	else
		bool = 0;
	end
end