%Autogenerated Test File
function bool = A8(vZ, vT, trace)
	cpd00022_c0_ = getColumn(trace, 'cpd00022_c0_');
	cpd00029_c0_ = getColumn(trace, 'cpd00029_c0_');
	if(checkColumns(cpd00022_c0_,cpd00029_c0_) == 0)
		bool = -1;
	elseif((1)*vT(cpd00022_c0_) + (1)*vT(cpd00029_c0_) == (1)*vZ(cpd00022_c0_) + (1)*vZ(cpd00029_c0_))
		bool = 1;
	else
		bool = 0;
	end
end