%Autogenerated Test File
function bool = A16(vZ, vT, trace)
	Reaction6 = getColumn(trace, 'Reaction6');
	cpd00020_c0_ = getColumn(trace, 'cpd00020_c0_');
	cpd00061_c0_ = getColumn(trace, 'cpd00061_c0_');
	cpd00169_c0_ = getColumn(trace, 'cpd00169_c0_');
	cpd00203_c0_ = getColumn(trace, 'cpd00203_c0_');
	cpd00482_c0_ = getColumn(trace, 'cpd00482_c0_');
	cpd11621_c0_ = getColumn(trace, 'cpd11621_c0_');
	if(checkColumns(Reaction6,cpd00020_c0_,cpd00061_c0_,cpd00169_c0_,cpd00203_c0_,cpd00482_c0_,cpd11621_c0_) == 0)
		bool = -1;
	elseif((1)*vT(Reaction6) + (-1)*vT(cpd00020_c0_) + (-1)*vT(cpd00061_c0_) + (-1)*vT(cpd00169_c0_) + (-1)*vT(cpd00203_c0_) + (-1)*vT(cpd00482_c0_) + (-1)*vT(cpd11621_c0_) == (1)*vZ(Reaction6) + (-1)*vZ(cpd00020_c0_) + (-1)*vZ(cpd00061_c0_) + (-1)*vZ(cpd00169_c0_) + (-1)*vZ(cpd00203_c0_) + (-1)*vZ(cpd00482_c0_) + (-1)*vZ(cpd11621_c0_))
		bool = 1;
	else
		bool = 0;
	end
end