%Autogenerated Test File
function bool = A19(vZ, vT, trace)
	Reaction9 = getColumn(trace, 'Reaction9');
	cpd00020_c0_ = getColumn(trace, 'cpd00020_c0_');
	cpd00061_c0_ = getColumn(trace, 'cpd00061_c0_');
	if(checkColumns(Reaction9,cpd00020_c0_,cpd00061_c0_) == 0)
		bool = -1;
	elseif((1)*vT(Reaction9) + (-1)*vT(cpd00020_c0_) + (-1)*vT(cpd00061_c0_) == (1)*vZ(Reaction9) + (-1)*vZ(cpd00020_c0_) + (-1)*vZ(cpd00061_c0_))
		bool = 1;
	else
		bool = 0;
	end
end