%Autogenerated Test File
function bool = A21(vZ, vT, trace)
	Reaction11 = getColumn(trace, 'Reaction11');
	cpd00029_c0_ = getColumn(trace, 'cpd00029_c0_');
	if(checkColumns(Reaction11,cpd00029_c0_) == 0)
		bool = -1;
	elseif((1)*vT(Reaction11) + (-1)*vT(cpd00029_c0_) == (1)*vZ(Reaction11) + (-1)*vZ(cpd00029_c0_))
		bool = 1;
	else
		bool = 0;
	end
end