%Autogenerated Test File
function bool = A7(vZ, vT, trace)
	cpd00001_c0_ = getColumn(trace, 'cpd00001_c0_');
	cpd00020_c0_ = getColumn(trace, 'cpd00020_c0_');
	cpd00061_c0_ = getColumn(trace, 'cpd00061_c0_');
	cpd11621_c0_ = getColumn(trace, 'cpd11621_c0_');
	if(checkColumns(cpd00001_c0_,cpd00020_c0_,cpd00061_c0_,cpd11621_c0_) == 0)
		bool = -1;
	elseif((1)*vT(cpd00001_c0_) + (-1)*vT(cpd00020_c0_) + (-1)*vT(cpd00061_c0_) + (-1)*vT(cpd11621_c0_) == (1)*vZ(cpd00001_c0_) + (-1)*vZ(cpd00020_c0_) + (-1)*vZ(cpd00061_c0_) + (-1)*vZ(cpd11621_c0_))
		bool = 1;
	else
		bool = 0;
	end
end